# Basic Intro + Arrays and Matrices

https://ucidatascienceinitiative.github.io/IntroToJulia/

## Intro

In [1]:
?broadcast # hunting down documentation - use the ? and any type/function/...

search: broadcast broadcast! Broadcast



```
broadcast(f, As...)
```

Broadcast the function `f` over the arrays, tuples, collections, [`Ref`](@ref)s and/or scalars `As`.

Broadcasting applies the function `f` over the elements of the container arguments and the scalars themselves in `As`. Singleton and missing dimensions are expanded to match the extents of the other arguments by virtually repeating the value. By default, only a limited number of types are considered scalars, including `Number`s, `String`s, `Symbol`s, `Type`s, `Function`s and some common singletons like [`missing`](@ref) and [`nothing`](@ref). All other arguments are iterated over or indexed into elementwise.

The resulting container type is established by the following rules:

  * If all the arguments are scalars or zero-dimensional arrays, it returns an unwrapped scalar.
  * If at least one argument is a tuple and all others are scalars or zero-dimensional arrays, it returns a tuple.
  * All other combinations of arguments default to returning an `Array`, but custom container types can define their own implementation and promotion-like rules to customize the result when they appear as arguments.

A special syntax exists for broadcasting: `f.(args...)` is equivalent to `broadcast(f, args...)`, and nested `f.(g.(args...))` calls are fused into a single broadcast loop.

# Examples

```jldoctest
julia> A = [1, 2, 3, 4, 5]
5-element Array{Int64,1}:
 1
 2
 3
 4
 5

julia> B = [1 2; 3 4; 5 6; 7 8; 9 10]
5×2 Array{Int64,2}:
 1   2
 3   4
 5   6
 7   8
 9  10

julia> broadcast(+, A, B)
5×2 Array{Int64,2}:
  2   3
  5   6
  8   9
 11  12
 14  15

julia> parse.(Int, ["1", "2"])
2-element Array{Int64,1}:
 1
 2

julia> abs.((1, -2))
(1, 2)

julia> broadcast(+, 1.0, (0, -2.0))
(1.0, -1.0)

julia> (+).([[0,2], [1,3]], Ref{Vector{Int}}([1,-1]))
2-element Array{Array{Int64,1},1}:
 [1, 1]
 [2, 2]

julia> string.(("one","two","three","four"), ": ", 1:4)
4-element Array{String,1}:
 "one: 1"
 "two: 2"
 "three: 3"
 "four: 4"

```


In [22]:
methods(copy) # pretty self explanatory

# 92 methods for generic function "copy":
[1] copy(e::Expr) in Base at expr.jl:36
[2] copy(c::Core.CodeInfo) in Base at expr.jl:64
[3] copy(s1::BitSet) in Base at bitset.jl:46
[4] copy(src::Random.DSFMT.DSFMT_state) in Random.DSFMT at C:\Users\Asus S\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\Random\src\DSFMT.jl:38
[5] copy(f::Random.DSFMT.GF2X) in Random.DSFMT at C:\Users\Asus S\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\Random\src\DSFMT.jl:111
[6] copy(src::Random.MersenneTwister) in Random at C:\Users\Asus S\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\Random\src\RNGs.jl:152
[7] copy(::Random._GLOBAL_RNG) in Random at C:\Users\Asus S\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\Random\src\RNGs.jl:324
[8] copy(md::Markdown.MD) in Markdown at C:\Users\Asus S\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\Markdown\src\parse\parse.jl:30
[9] copy(B::LinearAlgebra.Adjoint{Bool,BitArray{2}}) in LinearAlgebra at C:\Users\Asus S\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\LinearAlgebra\src\bitarray.jl:225
[10] copy(B::LinearAlgebra.Transpose{Bool,BitArray{2}}) in LinearAlgebra at C:\Users\Asus S\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\LinearAlgebra\src\bitarray.jl:226
[11] copy(vs::Pkg.Types.VersionSpec) in Pkg.Types at C:\Users\Asus S\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\Pkg\src\versions.jl:208
[12] copy(data::Pkg.Resolve.GraphData) in Pkg.Resolve at C:\Users\Asus S\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\Pkg\src\Resolve\graphtype.jl:165
[13] copy(graph::Pkg.Resolve.Graph) in Pkg.Resolve at C:\Users\Asus S\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\Pkg\src\Resolve\graphtype.jl:373
[14] copy(a::Pkg.Resolve.VersionWeight) in Pkg.Resolve at C:\Users\Asus S\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\Pkg\src\Resolve\versionweights.jl:39
[15] copy(a::Pkg.Resolve.FieldValue) in Pkg.Resolve at C:\Users\Asus S\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\Pkg\src\Resolve\fieldvalues.jl:63
[16] copy(r::AbstractRange) in Base at range.jl:582
[17] copy(x::Number) in Base at number.jl:88
[18] copy(a::T) where T<:Array in Base at array.jl:352
[19] copy(a::SubArray{#s664,#s663,#s662,I,L} where L where I where #s662<:Union{SparseArrays.AbstractSparseMatrixCSC, SparseArrays.SparseVector} where #s663 where #s664) in SparseArrays at C:\Users\Asus S\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\SparseArrays\src\sparsevector.jl:702
[20] copy(V::SubArray) in Base at subarray.jl:77
[21] copy(S::LinearAlgebra.Transpose{#s664,#s663} where #s663<:LinearAlgebra.SymTridiagonal where #s664) in LinearAlgebra at C:\Users\Asus S\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\LinearAlgebra\src\tridiag.jl:140
[22] copy(tS::LinearAlgebra.Transpose{#s664,#s663} where #s663<:LinearAlgebra.Tridiagonal where #s664) in LinearAlgebra at C:\Users\Asus S\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\LinearAlgebra\src\tridiag.jl:552
[23] copy(A::LinearAlgebra.Transpose{#s664,#s663} where #s663<:LinearAlgebra.LowerTriangular where #s664) in LinearAlgebra at C:\Users\Asus S\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\LinearAlgebra\src\triangular.jl:400
[24] copy(A::LinearAlgebra.Transpose{#s664,#s663} where #s663<:LinearAlgebra.UpperTriangular where #s664) in LinearAlgebra at C:\Users\Asus S\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\LinearAlgebra\src\triangular.jl:401
[25] copy(A::LinearAlgebra.Transpose{#s664,#s663} where #s663<:LinearAlgebra.UnitLowerTriangular where #s664) in LinearAlgebra at C:\Users\Asus S\AppData\Local\JuliaPro-1.4.1-1\Julia-1.4.1\share\julia\stdlib\v1.4\LinearAlgebra\src\triangular.jl:402
[26] copy(A::LinearAlgebra.Transpose{#s664,#s663} where #s663<:LinearAlgebr

In [29]:
# finding a type's fields? what are fields ? -> 

fieldnames(SubArray)

(:parent, :indices, :offset1, :stride1)

In [31]:
# finging out whih method is used when calling a function
@which broadcast(+, 2:5, 5:10) 

broadcast(f::Tf, As...) where Tf in Base.Broadcast at broadcast.jl:758

In [33]:
# and ofc a very simple way of finding what the type is
typeof([1;2;3])

Array{Int64,1}

### Strict typing and stuff
To achieve C/Fortran speed, Julia needs to be type strict - having a function work with a specific Type only. That's why functions have multiple methods - to cover all the combinations of types. (multiple-dispatch)

Writing stable functions is a must to achieve good performance. \
A way of checking whether a function is type-stable is using the macro \
@code_warntype \
To see where our type-stability goes wrong. \
To be even more specific we can use Traceur.jl \
\
using Traceur \
@trace \
-> returns what the return type is, and then we can see if this aligns with what we planned

### Global variables - scopes

Julia deals terribly with globals. 

If we do this for example. \
a = 3 \
function = badIdea() \
....a + 2 \
end \
a = 3.0 

Now, a is not type-stable, so at compile time, Julia doesn't know which type a is and since badIdea() is not specialized, we get unoptimized performance... \

To work around this, we can define constants (const) that let's Julia know what type the function will be using. \

"This is a very easy problem to fall for: don't benchmark or time things \
on the REPL's global scope. Always wrap things in a function or declare them as const."

In [38]:
# Creating a length 5 vector, with undefined values
a = Vector{Float64}(undef,5)

5-element Array{Float64,1}:
 1.905623054e-315
 7.755867e-316
 7.755867e-316
 7.755867e-316
 1.90562266e-315

In [36]:
a = [1;2;3;4;5] # COLUMN VECTOR - with ;

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [39]:
a = [1 2 3 4] # ROW VECTOR - space

1×4 Array{Int64,2}:
 1  2  3  4

In [40]:
# changing an element
a[2] = 10

10

In [42]:
# define an empty matrix
b = Matrix{Float64}(undef, 4, 2) # row, column

4×2 Array{Float64,2}:
 7.75499e-316  7.75499e-316
 7.77052e-316  7.75499e-316
 7.77052e-316  7.75499e-316
 7.75499e-316  1.73781e-315

In [47]:
c = Array{Float64}(undef, 4, 5, 6, 7) # -> 7 sets of 6 matrices, with 5 columns and 4 rows ?! what's the use case of this?

4×5×6×7 Array{Float64,4}:
[:, :, 1, 1] =
  1.21622e-62    3.455e-188      2.67063e-163    1.81704e-130  2.6048e-163
  5.55118e-246   2.50053e-265    8.33114e-178  NaN             4.53629e111
 -3.39154e100    1.43466e-284  NaN               9.58015e-164  1.22467e-225
  7.85492e-294  -0.00010686      6.30343e-260    1.22467e-225  3.20668e-289

[:, :, 2, 1] =
 6.65763e-294  7.8347e-308   5.18223e-281  1.35736e-100  2.9748e-283
 1.04484e-163  1.21626e-224  7.46634e-299  1.87991e-293  2.44646e-226
 5.18223e-281  1.35735e-100  1.12192e-307  1.48348e-105  6.92625e-293
 7.46631e-299  1.04484e-163  1.21626e-224  9.58015e-164  7.79569e-292

[:, :, 3, 1] =
     -7.22083e-9    -0.000107069   -1.07166e-8    -1.21132e-8   5.24978e-10
     -7.45686e-9     4.20066e-309   3.30201e-289   1.54939e58   9.34149e-15
 161776.0            2.35386e-293   8.39787e38     6.72635e14   1.2798e-57
      5.64095e-293   7.01368e-57    3.24375e-289   1.61143e-83  8.26501e-62

[:, :, 4, 1] =
   3.06748e-226  1.13419e-1

In [50]:
mat = [1 2 3 4
        3 4 5 6
        4 4 4 6
        3 3 3 3]
# same as writing -> mat = [1 2 3 4;3 4 5 6; 4 4 4 6; 3 3 3 3] - separating the row entries with space and columns with ;

In [52]:
# changing a matrix element
mat[2,3] = 101001
mat

4×4 Array{Int64,2}:
 1  2       3  4
 3  4  101001  6
 4  4       4  6
 3  3       3  3

In [55]:
a = [1;2;3]
b = a
b[1] = 9
a

3-element Array{Int64,1}:
 9
 2
 3

In [57]:
# to set one array = to another, use copy, now the first remains the same
b = copy(a)
b[1] = 100
a

3-element Array{Int64,1}:
 9
 2
 3

In [60]:
# one = ones(a) - ones() doesn't seem to work
c = similar(a) # an empty array of same shape, but elements seem to be random? how are they defined?
d = zero(a) # same shape with 0's

3-element Array{Int64,1}:
 0
 0
 0

In [62]:
# indexing made easy, f**k python haha
a[1:3] 
a[2:end]# Julia uses end instead of -1

2-element Array{Int64,1}:
 2
 3

In [65]:
# Arrays can be of any type! array inception :3
a = Vector{Vector{Float64}}(undef, 3)
a[1] = [1;2;3]
a[2] = [9;8;7]
a[3] = [6;4;5]
a

3-element Array{Array{Float64,1},1}:
 [1.0, 2.0, 3.0]
 [9.0, 8.0, 7.0]
 [6.0, 4.0, 5.0]

In [66]:
# Question 1
b = a
b[1] = [0;0;0]
a # we just pointed to the memory location, we didn't make a copy, causing a to change as we change b

3-element Array{Array{Float64,1},1}:
 [0.0, 0.0, 0.0]
 [9.0, 8.0, 7.0]
 [6.0, 4.0, 5.0]

In [69]:
# deepcopy - recursive copy function
b = deepcopy(a) # what's the difference between deep and normal copy? tried copy, nothing different...
b[1] = [1;2;3]
a

3-element Array{Array{Float64,1},1}:
 [0.0, 0.0, 0.0]
 [9.0, 8.0, 7.0]
 [6.0, 4.0, 5.0]

### Mutating functions

adding a ! after a function changes the first argument given after the exclamation mark
- crucial for Julia's performance

In [72]:
a = [1;6;8]
b = similar(a)
copyto!(b,a)

3-element Array{Int64,1}:
 1
 6
 8

### Control Flow
- for, while loops and if statements

seems much, much more intuitive and natural than Python

In [78]:
# for i = 1:5
#     println(i)
# end

t = 0
while t < 5
    println(t)
    t += 1
end

# :UCI - is a symbol?! what is a symbol? a string?

UCI


In [92]:
# SUPER COOL FEATURE, love this
# two loops defined in one place - a nested loop 

for i=1:2,j=2:4;
    println("$i $j")
end

# SAME AS
# for i in 1:2
#     for j in 2:4
#         println("$i $j")
#     end
# end

1 2
1 3
1 4
2 2
2 3
2 4


## Arrays

### Operations, Broadcast,  Memory

In [4]:
A = map((x)-> x^2, 1:10) # unusual syntax? looks simple though

In [9]:
A = 1:5 # acts as a column vector! it is not a column vector until we do sth with it?! 
B = [1 2
     3 4
     5 6
     7 8
     9 10]
broadcast(+, A, B) # casts the first param operator to the other arguments

5×2 Array{Int64,2}:
  2   3
  5   6
  8   9
 11  12
 14  15

adding a . in front of an opreation is the same as broadcasting it

In [1]:
A = 1:5
B = [2;3;4;5;6] # same as 2:6
A.*B # same as broadcast(*, A, B)

5-element Array{Int64,1}:
  2
  6
 12
 20
 30

In [2]:
C = [3;4;5;2;1]
A.*B.*C # == .*(A, .*(B, C))

5-element Array{Int64,1}:
  6
 24
 60
 40
 30

In [9]:
# implementation of broadcasting

function broadcast_mult(x, y)
    out = similar(x)
    for i in eachindex(x)
        out[i] = x[i] * y[i]
    end
    out
end

broadcast_mult(A, B);
# instead of A.*B.*C -> broadcast can take an anonymous function and do broadcasts on it
broadcast((x,y,z)->x*y*z, A, B, C)

5-element Array{Int64,1}:
  6
 24
 60
 40
 30

In [15]:
# also possible to broadcast = (.=)
# D = similar(C)

# using BenchmarkTools
@btime D.=A.*B.*C # slightly faster then doing D = A.*B.*C

# broadcasting makes operations element-wise, not allocating and arrays -> making it faster

  594.286 ns (4 allocations: 96 bytes)


5-element Array{Int64,1}:
  6
 24
 60
 40
 30

In [75]:
A = rand(4,4)

A[1:3, 1:3] # allocates memory for the newly created array

3×3 Array{Float64,2}:
 0.449931   0.00856122  0.891517
 0.0432072  0.986272    0.366697
 0.284018   0.00954201  0.997359

In [7]:
a = [1;3;5]

@time b = a # does not allocate memory, just points to it
a[2] = 10 # now changes both a and b
a, b

@time c = copy(a) # needs to allocate memoery for a new array, takes significantly more time

  0.000000 seconds
  0.001595 seconds (28 allocations: 2.031 KiB)


3-element Array{Int64,1}:
  1
 10
  5

Arrays as we see it are just a 'view' to the one dimensional number sequence in memory. 
-> Indexes the sequence in a way that we see 2 dimensions, which is why looping through columns is faster than through rows. 

In [52]:
function testloops()
    b = rand(1000, 1000)
    c = 0
    @time for i in 1:1000, j in 1:1000
        c += b[i,j] 
    end
    @time for j in 1:1000, i in 1:1000
        c += b[i,j]
    end
    bidx = eachindex(b)
    @time for i in bidx
        c += b[i]
    end
end
testloops()

  0.000599 seconds
  0.000310 seconds
  0.000523 seconds


The fast iteration is with eachindex()!!!

In [59]:
# BUT, when we slice the array, it is no longer pointing to the same memory
println(A)
B = A[1:3, 1:3]
B[1,1] = 1000
println(A)
println(B) # only changed @ B

[0.2934400518796758 0.6309219678654696 0.32481215128341856 0.6096984317669494; 0.4971621542192126 0.709649306786291 0.6367784950150404 0.8105486628195255; 0.4772302552861003 0.229867299404924 0.11865800344296407 0.3404485893124416; 0.8776805264724348 0.6838057179970138 0.3793194158509088 0.8737267618497815]
[0.2934400518796758 0.6309219678654696 0.32481215128341856 0.6096984317669494; 0.4971621542192126 0.709649306786291 0.6367784950150404 0.8105486628195255; 0.4772302552861003 0.229867299404924 0.11865800344296407 0.3404485893124416; 0.8776805264724348 0.6838057179970138 0.3793194158509088 0.8737267618497815]
[1000.0 0.6309219678654696 0.32481215128341856; 0.4971621542192126 0.709649306786291 0.6367784950150404; 0.4772302552861003 0.229867299404924 0.11865800344296407]


In [84]:
# id we want the same memoery location, use view()
B = view(A, 1:3, 1:3)
B[1,1] = 999 # then when we change B, we also change A
A

4×4 Array{Float64,2}:
 999.0       0.787645  0.439098  0.940952
   0.366572  0.189643  0.471893  0.288471
   0.813142  0.313396  0.849975  0.264878
   0.784032  0.700011  0.571713  0.182147

We might want to use view() when passing a slice to a function, and we do want to change the original array

In [76]:
c = vec(A) #
C = reshape(A, 8, 2) # as usual Row, Column
C

8×2 Array{Float64,2}:
 0.449931    0.891517
 0.0432072   0.366697
 0.284018    0.997359
 0.543507    0.390266
 0.00856122  0.00831681
 0.986272    0.521532
 0.00954201  0.412563
 0.25692     0.184783

### Linear Algebra

Multithreaded operation * on matrices.

In [79]:
A = rand(4, 4); B = rand(4, 4)
C = A*B # matrix multiplication
D = A.*B # element-wise multiplication!

4×4 Array{Float64,2}:
 0.0851134  0.666479  0.096151  0.816758
 0.162674   0.152241  0.388435  0.108922
 0.393204   0.136352  0.256049  0.0950968
 0.335479   0.538701  0.446513  0.0604

In [82]:
b = 1:4
A\b # solving for Ax = b

4-element Array{Float64,1}:
 -15.400073004251766
  11.581644729530648
  16.534629980981624
  -8.159283482877514

In [85]:
# Spares matrices
# -> table format, triplets (i, j, value)
using SparseArrays
A = sparse([1;2;3], [2;2;1], [3;4;5])

3×2 SparseMatrixCSC{Int64,Int64} with 3 stored entries:
  [3, 1]  =  5
  [1, 2]  =  3
  [2, 2]  =  4

In [86]:
Array(A)

3×2 Array{Int64,2}:
 0  3
 0  4
 5  0

In [87]:
# Diagonal, tridiagonal...
# always better to use than sparse or dense matrices, since these special matrices
# use less memory, for example this tridiagonal - only has 3 vectors stored(perhaps four including du2?)
using LinearAlgebra
A = Tridiagonal(2:5, 1:5, 1:4)

5×5 Tridiagonal{Int64,UnitRange{Int64}}:
 1  1  ⋅  ⋅  ⋅
 2  2  2  ⋅  ⋅
 ⋅  3  3  3  ⋅
 ⋅  ⋅  4  4  4
 ⋅  ⋅  ⋅  5  5

In [88]:
fieldnames(typeof(A)) # dl - diagonal lower, d - main diagonal, du - diagonal upper, du2 - no idea? 

(:dl, :d, :du, :du2)

In [97]:
A.*rand(5,5) # operations work regularly

5×5 Array{Float64,2}:
 0.117234  0.638521   0.0      0.0      0.0
 1.41415   0.0786699  1.04882  0.0      0.0
 0.0       1.74673    2.10954  2.58151  0.0
 0.0       0.0        3.10263  1.43459  0.640136
 0.0       0.0        0.0      2.51949  1.3456

In [98]:
# Smart identity matrix - never forms a matrix, but acts as one whenever we need it
# to subtract a scalar from a matrix
A = rand(5,5)
λ = 2
A - λ*I

5×5 Array{Float64,2}:
 -1.96004     0.785822   0.693955   0.127172    0.0123761
  0.0192172  -1.81184    0.993417   0.655862    0.753028
  0.142131    0.163492  -1.69051    0.515506    0.00162102
  0.114023    0.343724   0.91573   -1.76859     0.0368716
  0.542405    0.900229   0.879457   0.0878307  -1.50012

In [99]:
# Factorizations made easy and with better performance
b = 1:5
A = rand(5,5)
q = qr(A)

LinearAlgebra.QRCompactWY{Float64,Array{Float64,2}}
Q factor:
5×5 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 -0.559036    0.341236    0.0631995   0.485864   0.575307
 -0.451624    0.0724077   0.744991   -0.106413  -0.47377
 -0.412696   -0.483519   -0.426191    0.45692   -0.453296
 -0.557487    0.0276817  -0.381115   -0.730151   0.100363
 -0.0490444  -0.802345    0.337798   -0.103512   0.478555
R factor:
5×5 Array{Float64,2}:
 -1.57045  -1.25394   -1.02109   -0.622988  -0.800371
  0.0      -0.751758  -0.746701  -0.480568  -0.393409
  0.0       0.0        0.623631  -0.319121  -0.327597
  0.0       0.0        0.0       -0.154988   0.0813965
  0.0       0.0        0.0        0.0       -0.37399

In [105]:
# then we can just
@time q\b

  0.000019 seconds (5 allocations: 624 bytes)


5-element Array{Float64,1}:
  0.16054228372519214
 -2.833236101737603
  4.373471739354354
 10.085966307275111
 -2.8399299458382012

In [107]:
l = lu(A)

LU{Float64,Array{Float64,2}}
L factor:
5×5 Array{Float64,2}:
 1.0        0.0        0.0       0.0       0.0
 0.0877302  1.0        0.0       0.0       0.0
 0.738227   0.883629   1.0       0.0       0.0
 0.997228   0.375604   0.742313  1.0       0.0
 0.807861   0.244224  -0.799534  0.211839  1.0
U factor:
5×5 Array{Float64,2}:
 0.877937  0.444474   0.355437  0.0888144   0.116876
 0.0       0.625674   0.828669  0.316588    0.0465883
 0.0       0.0       -0.477972  0.209346    0.739421
 0.0       0.0        0.0       0.205911   -0.219741
 0.0       0.0        0.0       0.0         0.789391

### Random number

In [109]:
rand(5) # uniform
randn(5, 5) # normal random

5×5 Array{Float64,2}:
 -0.892673  -0.974521   -1.28372   -0.0480631  -0.556884
 -0.122791  -1.63404     0.781767   0.600983    0.302176
 -0.375285  -1.08624     0.302118  -1.42489     1.07378
 -1.35009    0.0592513  -0.565259   0.464772   -2.47376
  2.28626   -1.21881    -0.649583   0.750118   -0.531164

In [111]:
a = [1 2
     3 4]
randn(size(a))

2×2 Array{Float64,2}:
 -0.799813   1.46584
 -1.50173   -0.396169